### ISSUE TITLE
Set topic when changing deploy status

### ISSUE THREAD

**Issue by NeoHuang** [andrewslotin/slack-deploy-command#3]
set topic to ⛔ when deploy and  to ✅  when finished

**Comment by NeoHuang** [comment]
for the record, the api is here https://api.slack.com/methods/channels.setTopic

example url `https://slack.com/api/channels.setTopic?token={token}&channel=C1E79M7T7&topic=%3Ano_entry%3A&pretty=1`

**Comment by andrewslotin** [comment]
I'd rather avoid mixing a slash command and an API consumer. Pretty sure Slackbot (or any other bot) can be scripted to react on some predefined messages and update topic.

**Comment by NeoHuang** [comment]
have you tried responsing `/topic :no_entry:`?

**Comment by andrewslotin** [comment]
Yes, Slack does not execute commands returned by other commands.

**Comment by NeoHuang** [comment]
the thing is make a bot is easy, but needs to submit to slack team to get reviewed. 
maybe as another option: extend this deploy command server to be able to call some callback when receive the message to remove the dependency

**Comment by NeoHuang** [comment]
👍
