### ISSUE TITLE
Make a dashboard to show all the deploy statistics

### ISSUE THREAD

**Issue by NeoHuang** [andrewslotin/slack-deploy-command#5]
it would be nice to have a dashboard to show all the deploy statistics like 
- the longest deploy, of all and for each individual
- the shortest deploy, of all and for each individual
- average deploy time
- heat map of deployment like the github calendar

and maybe others 

/cc @andrewslotin 

for that we need a db or key-value storage, what do you prefer?

**Comment by andrewslotin** [comment]
Great idea! I'd also consider keeping deploy history (what was deployed when and by whom). I think something like https://github.com/boltdb/bolt would be a good default option as I'd like to keep this project free from external dependencies by default.
